### PR TITLE
Fixes problem with sign requiring a HashcheckTicket.

### LINKED ISSUE #475: No way to sign without hashcheck ticket
https://docs.rs/tss-esapi/latest/tss_esapi/struct.Context.html#method.sign requires a hashcheck ticket, however an unrestricted key should not *need* the hashcheck. Should there be two sign apis, one for restricted_sign and one for unrestricted? 

Or am I overlooking something obvious here?

### PR DESCRIPTION
**Pull request by Superhepper**
- This fixes #475 by making the HashcheckTicket that was previously required in the ```sign``` context method optional instead. If it is ```None``` it is then internally converted into the HashcheckTicket version of the `Null ticket` before being converted to the corresponding TSS type. This has the benefit of removing the need to use the TSS type in order to create a `Null ticket`.

### CODE REVIEW

**Review by Firstyear — COMMENTED** [review]
I can't see the changes to `fn sign` here, were they committed?

File: tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs [hunk 1]
```diff
@@ -45,9 +45,10 @@ impl Context {
         key_handle: KeyHandle,
         digest: Digest,
         scheme: SignatureScheme,
-        validation: HashcheckTicket,
+        validation: Option<HashcheckTicket>,
```
Comment (wiktor-k) [inline tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs:48]: I think it looks good but just for the sake of completeness, to avoid API breaks you could make `validation: impl Into<Option<HashcheckTicket>>` and below add a call to `.into()` before `.unwrap_or_default()`.

This would allow clients to call this function with `HashcheckTickets` like previously (no modification needed, no Some wrapping) but would also accept `None`.

An example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f509608362b096375d913dbed0a29a88

**Review by wiktor-k — APPROVED** [review]
This makes a lot of calling code cleaner. Thanks! :+1:

**Comment by wiktor-k** [comment]
> I can't see the changes to `fn sign` here, were they committed?

I think you were looking for [this line of code](https://github.com/parallaxsecond/rust-tss-esapi/pull/476/files#diff-b349ca1f38d7200781cc5f9e14f2cd3cfefa3bc5ad07a6f406248ae2b9643ed4R43).

File: tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs (hunk 1 above)
Comment (Superhepper) [reply tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs]: That is neat I added it.

**Review by wiktor-k — APPROVED** [review]

File: tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs [hunk 2]
```diff
@@ -45,9 +45,10 @@ impl Context {
         key_handle: KeyHandle,
         digest: Digest,
         scheme: SignatureScheme,
-        validation: HashcheckTicket,
+        validation: impl Into<Option<HashcheckTicket>>,
```
Comment (ionut-arm) [inline tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs:48]: I guess since the docs on this method are fairly lightweight, there's no point in specifying what happens if one passes `None` here?

**Review by ionut-arm — APPROVED** [review]
Awesome, thanks!

File: tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs (hunk 2 above)
Comment (Firstyear) [reply tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs:48]: It's probably better to say something here since we're looking. Maybe something like:

"For signatures using a restricted key, a hashcheck must be provided. For unrestricted keys, this may be None"

Comment (Superhepper) [reply tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs:48]: Yes, I should probably also update the documentation of the sign context method while I am at because it was seriously lacking.

Comment (Superhepper) [reply tss-esapi/src/context/tpm_commands/signing_and_signature_verification.rs:99]: Please have a look at the documentation that I added and see if it seems alright.

**Review by Firstyear — APPROVED** [review]
Looks good mate!

**Review by wiktor-k — DISMISSED** [review]
LGTM :+1: thanks!

This got me thinking that maybe we should review the other parameters and allow `None`s there too :sweat_smile:

**Comment by Superhepper** [comment]
> LGTM 👍 thanks!
> 
> This got me thinking that maybe we should review the other parameters and allow `None`s there too 😅

I am not so sure about that. The other parameters have actual ```Null``` options which the ticket didn't.

File: tss-esapi/src/structures/tickets.rs [hunk 3]
```diff
@@ -124,6 +127,17 @@ pub struct HashcheckTicket {
     digest: Vec<u8>,
 }
 
+impl Default for HashcheckTicket {
+    /// The default for the Hashcheck ticket is the Null ticket.
+    fn default() -> Self {
+        Self {
+            tag: StructureTag::Hashcheck,
+            hierarchy: Hierarchy::Null,
+            digest: Vec::<u8>::new(),
```
Comment (wiktor-k) [inline tss-esapi/src/structures/tickets.rs:136]: :thinking: This is minor but I think the `::<u8>` part is redundant.

**Review by wiktor-k — APPROVED** [review]
LGTM :+1:

**Comment by Superhepper** [comment]
> Awesome, thanks!

Could you also add a review for this?

**Review by ionut-arm — APPROVED** [review]
LGTM, thanks for the documentation
